### ISSUE TITLE
Error count() Parameter must be an array or an object

### ISSUE THREAD

**Issue by sixdominent** [vdomah/oc-translatetabs#2]
"count(): Parameter must be an array or an object that implements Countable" on line 48 of ...\octobercms\plugins\vdomah\translatetabs\Plugin.php

I found it is an error with PHP 7.2
I change \octobercms\plugins\vdomah\translatetabs\Plugin.php at line 48 

from
```
if (!count($arr))
    return false;
```

to
```
if (is_array($arr)) {
    if (!count($arr))
        return false;
} else {
    return false;
}
```

It is worked!

**Comment by jeremymouton** [comment]
For anyone else running in to this, updating October CMS and rainlab/translate-plugin to the latest fixes the issue.

**Comment by vdomah** [comment]
applied in v1.0.4. Thanks!
